import os

RESET_PASSWORD_TOKEN_SECRET = os.environ["RESET_PASSWORD_TOKEN_SECRET"]
RESET_PASSWORD_VERIFICATION_TOKEN_SECRET = os.environ[
    "RESET_PASSWORD_VERIFICATION_TOKEN_SECRET"
]
SESSION_EXPIRE_TIME_SECONDS = int(os.environ.get("SESSION_EXPIRE_TIME_SECONDS", 3600))
