apiVersion: keda.sh/v1alpha1
kind: ScaledObject
metadata:
  name: indexing-model-server-scaledobject
  namespace: onyx
  labels:
    app: indexing-model-server
spec:
  scaleTargetRef:
    name: indexing-model-server-deployment
  pollingInterval: 15 # Check every 15 seconds
  cooldownPeriod: 30 # Wait 30 seconds before scaling down
  minReplicaCount: 10
  maxReplicaCount: 10
  triggers:
    - type: cpu
      metadata:
        type: Utilization
        value: "70"
