"""added-pruning-field

Revision ID: 0300163d51ea
Revises: b85f02ec1308
Create Date: 2024-06-15 20:56:46.014861

"""
from alembic import op
import sqlalchemy as sa

# revision identifiers, used by Alembic.
revision = "0300163d51ea"
down_revision = "b85f02ec1308"
branch_labels = None  # type: ignore
depends_on = None  # type: ignore


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    # op.add_column(
    #     "connector",
    #     sa.Column("pruning_freq", sa.Boolean(), nullable=False),
    # )
    # op.execute("UPDATE connector SET pruning_freq = None")
    # op.alter_column("connector", "pruning_freq", nullable=False)

    # op.add_column(
    #     "index_attempt", sa.Column("pruning_attempt", sa.Boolean(), nullable=True)
    # )
    # op.execute("UPDATE index_attempt SET pruning_attempt = False")

    op.add_column(
        "index_attempt",
        sa.Column(
            "input_type",
            sa.Enum(
                "LOAD_STATE",
                "POLL",
                "EVENT",
                "PRUNE",
                name="inputtype",
                native_enum=False,
            ),
            nullable=True,
        ),
    )
    op.drop_column("connector", "input_type")
    # sa.Column(
    #     "input_type",
    #     sa.Enum(
    #         "LOAD_STATE",
    #         "POLL",
    #         "EVENT",
    #         name="inputtype",
    #         native_enum=False,
    #     ),
    #     nullable=True,
    # ),
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    # op.drop_column("index_attempt", "pruning_attempt")
    # op.drop_column("connector", "pruning_freq")
    op.drop_column("index_attempt", "input_type")
    op.add_column(
        "connector",
        sa.Column(
            "input_type",
            sa.Enum(
                "LOAD_STATE",
                "POLL",
                "EVENT",
                name="inputtype",
                native_enum=False,
            ),
            nullable=True,
        ),
    )
    # ### end Alembic commands ###
