"""Add workspace user role and migrate data

Revision ID: 17ca0f0827de
Revises: a2d61fc58c5b
Create Date: 2024-11-12 17:20:39.674425

"""
from alembic import op
import sqlalchemy as sa
from sqlalchemy.orm import Session
from sqlalchemy import text

# revision identifiers, used by Alembic.
revision = "17ca0f0827de"
down_revision = "a2d61fc58c5b"
branch_labels = None
depends_on = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column(
        "workspace__users",
        sa.Column(
            "role",
            sa.Enum("BASIC", "ADMIN", name="userrole", native_enum=False),
            nullable=False,
            server_default="BASIC",
        ),
    )
    # ### end Alembic commands ###

    # Copy data from `user` table to `workspace__users`
    migrate_users_to_workspace_users()


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_column("workspace__users", "role")
    # ### end Alembic commands ###


def migrate_users_to_workspace_users():
    # Establish a database connection
    bind = op.get_bind()
    session = Session(bind=bind)

    # Copy users from `user` table to `workspace__users` table
    try:
        session.execute(
            text(
                """
                INSERT INTO workspace__users (workspace_id, user_id, role)
                SELECT 0, id, role
                FROM "user"
                """
            )
        )
        session.commit()
    except Exception as e:
        session.rollback()
        print(f"Error migrating users: {e}")
    finally:
        session.close()
