"""settings database table

Revision ID: 24cad828e24c
Revises: 4644a2459b2b
Create Date: 2024-10-10 19:55:14.464493

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = "24cad828e24c"
down_revision = "4644a2459b2b"
branch_labels = None
depends_on = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table(
        "teamspace_settings",
        sa.Column("id", sa.Integer(), nullable=False),
        sa.Column("chat_page_enabled", sa.Boolean(), nullable=False),
        sa.Column("search_page_enabled", sa.Boolean(), nullable=False),
        sa.Column("chat_history_enabled", sa.Boolean(), nullable=False),
        sa.Column(
            "default_page",
            sa.Enum("CHAT", "SEARCH", name="pagetype", native_enum=False),
            nullable=False,
        ),
        sa.Column("maximum_chat_retention_days", sa.Integer(), nullable=True),
        sa.Column("teamspace_id", sa.Integer(), nullable=True),
        sa.ForeignKeyConstraint(
            ["teamspace_id"],
            ["teamspace.id"],
        ),
        sa.PrimaryKeyConstraint("id"),
    )
    op.create_table(
        "workspace_settings",
        sa.Column("id", sa.Integer(), nullable=False),
        sa.Column("chat_page_enabled", sa.Boolean(), nullable=False),
        sa.Column("search_page_enabled", sa.Boolean(), nullable=False),
        sa.Column(
            "default_page",
            sa.Enum("CHAT", "SEARCH", name="pagetype", native_enum=False),
            nullable=False,
        ),
        sa.Column("maximum_chat_retention_days", sa.Integer(), nullable=True),
        sa.Column("num_indexing_workers", sa.Integer(), nullable=False, default=1),
        sa.Column("vespa_searcher_threads", sa.Integer(), nullable=False, default=2),
        sa.Column("workspace_id", sa.Integer(), nullable=True),
        sa.ForeignKeyConstraint(
            ["workspace_id"],
            ["workspace.id"],
        ),
        sa.PrimaryKeyConstraint("id"),
    )
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_table("workspace_settings")
    op.drop_table("teamspace_settings")
    # ### end Alembic commands ###
