"""fix migration

Revision ID: 2c084e6c102a
Revises: 3a7802814195
Create Date: 2024-08-15 17:31:25.978543

"""
from alembic import op
import sqlalchemy as sa
import fastapi_users_db_sqlalchemy

# revision identifiers, used by Alembic.
revision = "2c084e6c102a"
down_revision = "3a7802814195"
branch_labels = None
depends_on = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table(
        "instance",
        sa.Column("id", sa.Integer(), nullable=False),
        sa.Column("instance_name", sa.Text(), nullable=False),
        sa.Column(
            "subscription_plan",
            sa.Enum(
                "ENTERPRISE",
                "PARTNER",
                name="instancesubscriptionplan",
                native_enum=False,
            ),
            nullable=False,
            default="ENTERPRISE",
        ),
        sa.Column(
            "owner_id",
            fastapi_users_db_sqlalchemy.generics.GUID(),
            nullable=True,
        ),
        sa.ForeignKeyConstraint(
            ["owner_id"],
            ["user.id"],
        ),
        sa.PrimaryKeyConstraint("id"),
    )
    op.create_table(
        "workspace",
        sa.Column("id", sa.Integer(), nullable=False),
        sa.Column("instance_id", sa.Integer(), nullable=True),
        sa.Column("Workspace_name", sa.Text(), nullable=False),
        sa.Column("custom_logo", sa.Text(), nullable=True),
        sa.Column("custom_header_logo", sa.Text(), nullable=True),
        sa.ForeignKeyConstraint(
            ["instance_id"],
            ["instance.id"],
        ),
        sa.PrimaryKeyConstraint("id"),
    )
    op.create_table(
        "workspace__users",
        sa.Column("workspace_id", sa.Integer(), nullable=False),
        sa.Column(
            "user_id",
            fastapi_users_db_sqlalchemy.generics.GUID(),
            nullable=False,
        ),
        sa.ForeignKeyConstraint(
            ["user_id"],
            ["user.id"],
        ),
        sa.ForeignKeyConstraint(
            ["workspace_id"],
            ["workspace.id"],
        ),
        sa.PrimaryKeyConstraint("workspace_id", "user_id"),
    )

    op.create_table(
        "workspace__teamspace",
        sa.Column("workspace_id", sa.Integer(), nullable=False),
        sa.Column("teamspace_id", sa.Integer(), nullable=False),
        sa.ForeignKeyConstraint(
            ["teamspace_id"],
            ["teamspace.id"],
        ),
        sa.ForeignKeyConstraint(
            ["workspace_id"],
            ["workspace.id"],
        ),
        sa.PrimaryKeyConstraint("workspace_id", "teamspace_id"),
    )
    op.add_column("teamspace", sa.Column("workspace_id", sa.Integer(), nullable=False))
    op.create_foreign_key(
        "teamspace_workspace_id_fk",
        "teamspace",
        "workspace",
        ["workspace_id"],
        ["id"],
    )
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_constraint("teamspace_workspace_id_fk", "teamspace", type_="foreignkey")
    op.drop_column("teamspace", "workspace_id")
    op.drop_table("workspace__teamspace")
    op.drop_table("workspace_settings")
    op.drop_table("workspace__users")
    op.drop_table("workspace")
    op.drop_table("instance")
    # ### end Alembic commands ###
