"""fix workspace table

Revision ID: 44d3c68af1f0
Revises: 900205f44357
Create Date: 2024-08-29 05:04:32.897658

"""
from alembic import op
import sqlalchemy as sa
from sqlalchemy.dialects import postgresql

# revision identifiers, used by Alembic.
revision = "44d3c68af1f0"
down_revision = "900205f44357"
branch_labels = None
depends_on = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_column("user", "workspace_id")
    op.drop_constraint("teamspace_workspace_id_fk", "teamspace", type_="foreignkey")
    op.drop_column("teamspace", "workspace_id")
    op.add_column("workspace", sa.Column("workspace_name", sa.Text(), nullable=False))
    op.drop_column("workspace", "Workspace_name")
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column(
        "workspace",
        sa.Column("Workspace_name", sa.TEXT(), autoincrement=False, nullable=False),
    )
    op.drop_column("workspace", "workspace_name")
    op.add_column(
        "teamspace",
        sa.Column("workspace_id", sa.INTEGER(), autoincrement=False, nullable=False),
    )
    op.create_foreign_key(
        "teamspace_workspace_id_fk",
        "teamspace",
        "workspace",
        ["workspace_id"],
        ["id"],
    )
    op.add_column(
        "user",
        sa.Column("workspace_id", sa.INTEGER(), autoincrement=False, nullable=True),
    )
    op.create_foreign_key(
        "user_workspace_id_fk",
        "user",
        "workspace",
        ["workspace_id"],
        ["id"],
    )
    op.create_unique_constraint("chat_message_id_key", "chat_message", ["id"])
    op.create_table(
        "kombu_message",
        sa.Column("id", sa.INTEGER(), autoincrement=False, nullable=False),
        sa.Column("visible", sa.BOOLEAN(), autoincrement=False, nullable=True),
        sa.Column(
            "timestamp",
            postgresql.TIMESTAMP(),
            autoincrement=False,
            nullable=True,
        ),
        sa.Column("payload", sa.TEXT(), autoincrement=False, nullable=False),
        sa.Column("version", sa.SMALLINT(), autoincrement=False, nullable=False),
        sa.Column("queue_id", sa.INTEGER(), autoincrement=False, nullable=True),
        sa.ForeignKeyConstraint(
            ["queue_id"], ["kombu_queue.id"], name="FK_kombu_message_queue"
        ),
        sa.PrimaryKeyConstraint("id", name="kombu_message_pkey"),
    )
    op.create_index(
        "ix_kombu_message_visible", "kombu_message", ["visible"], unique=False
    )
    op.create_index(
        "ix_kombu_message_timestamp_id",
        "kombu_message",
        ["timestamp", "id"],
        unique=False,
    )
    op.create_index(
        "ix_kombu_message_timestamp",
        "kombu_message",
        ["timestamp"],
        unique=False,
    )
    op.create_table(
        "kombu_queue",
        sa.Column("id", sa.INTEGER(), autoincrement=False, nullable=False),
        sa.Column("name", sa.VARCHAR(length=200), autoincrement=False, nullable=True),
        sa.PrimaryKeyConstraint("id", name="kombu_queue_pkey"),
        sa.UniqueConstraint("name", name="kombu_queue_name_key"),
    )
    # ### end Alembic commands ###
