"""add cloud embedding model and update embedding_model

Revision ID: 44f856ae2a4a
Revises: bc9771dccadf
Create Date: 2024-06-28 20:01:05.927647

"""
from alembic import op
import sqlalchemy as sa
from sqlalchemy.dialects import postgresql

# revision identifiers, used by Alembic.
revision = "44f856ae2a4a"
down_revision = "bc9771dccadf"
branch_labels = None
depends_on = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table(
        "embedding_provider",
        sa.Column("id", sa.Integer(), nullable=False),
        sa.Column("name", sa.String(), nullable=False),
        sa.Column("provider_id", sa.String(), nullable=False),
        sa.Column("api_key", sa.String(), nullable=True),
        sa.Column("api_base", sa.String(), nullable=True),
        sa.Column("api_version", sa.String(), nullable=True),
        sa.Column("custom_config", sa.JSON(), nullable=True),
        sa.Column("default_model_name", sa.String(), nullable=False),
        sa.Column(
            "model_names", postgresql.ARRAY(sa.String()), nullable=False
        ),
        sa.Column("is_configured", sa.Boolean(), nullable=False),
        sa.Column("is_default_provider", sa.Boolean(), nullable=True),
        sa.PrimaryKeyConstraint("id"),
        sa.UniqueConstraint("is_default_provider"),
        sa.UniqueConstraint("name"),
        sa.UniqueConstraint("provider_id"),
    )

    # Add new column to embedding_model table
    op.add_column('embedding_model', sa.Column('cloud_provider_id', sa.Integer(), nullable=True))
    
    # Add foreign key constraint
    op.create_foreign_key(
        "fk_embedding_model_cloud_provider",
        "embedding_model",
        "embedding_provider",
        ["cloud_provider_id"],
        ["id"]
    )

    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    
    # Remove foreign key constraint
    op.drop_constraint("fk_embedding_model_cloud_provider", "embedding_model", type_="foreignkey")
    
    # Remove cloud_provider_id column
    op.drop_column('embedding_model', 'cloud_provider_id')
    
    # Drop embedding_provider table
    op.drop_table("embedding_provider")
    
    # ### end Alembic commands ###