"""chat_folder__teamspace relationship table

Revision ID: 4644a2459b2b
Revises: 8487a94e1e38
Create Date: 2024-10-01 20:50:16.637771

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = "4644a2459b2b"
down_revision = "8487a94e1e38"
branch_labels = None
depends_on = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table(
        "chat_folder__teamspace",
        sa.Column("chat_folder_id", sa.Integer(), nullable=False),
        sa.Column("teamspace_id", sa.Integer(), nullable=False),
        sa.ForeignKeyConstraint(
            ["chat_folder_id"],
            ["chat_folder.id"],
        ),
        sa.ForeignKeyConstraint(
            ["teamspace_id"],
            ["teamspace.id"],
        ),
        sa.PrimaryKeyConstraint("chat_folder_id", "teamspace_id"),
    )
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_table("chat_folder__teamspace")
    # ### end Alembic commands ###
