"""removed danswerbot_flow from chat session table

Revision ID: 46eb3f54ab5b
Revises: 44d3c68af1f0
Create Date: 2024-08-29 13:48:18.828549

"""
from alembic import op
import sqlalchemy as sa

# revision identifiers, used by Alembic.
revision = "46eb3f54ab5b"
down_revision = "44d3c68af1f0"
branch_labels = None
depends_on = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_column("chat_session", "danswerbot_flow")
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column(
        "chat_session",
        sa.Column(
            "danswerbot_flow",
            sa.BOOLEAN(),
            autoincrement=False,
            nullable=False,
        ),
    )
    # ### end Alembic commands ###
