"""Add type to credentials

Revision ID: 4ea2c93919c1
Revises: 325975216eb3
Create Date: 2024-07-18 13:07:13.655895

"""

from alembic import op
import sqlalchemy as sa

# revision identifiers, used by Alembic.
revision = "4ea2c93919c1"
down_revision = "325975216eb3"
branch_labels = None
depends_on = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    # Add the new 'source' column to the 'credential' table
    op.add_column(
        "credential",
        sa.Column(
            "source",
            sa.Enum(
                "INGESTION_API",
                "SLACK",
                "WEB",
                "GOOGLE_DRIVE",
                "GMAIL",
                "REQUESTTRACKER",
                "GITHUB",
                "GITLAB",
                "GURU",
                "BOOKSTACK",
                "CONFLUENCE",
                "SLAB",
                "JIRA",
                "PRODUCTBOARD",
                "FILE",
                "NOTION",
                "ZULIP",
                "LINEAR",
                "HUBSPOT",
                "DOCUMENT360",
                "GONG",
                "GOOGLE_SITES",
                "ZENDESK",
                "LOOPIO",
                "DROPBOX",
                "SHAREPOINT",
                "TEAMS",
                "SALESFORCE",
                "DISCOURSE",
                "AXERO",
                "CLICKUP",
                "MEDIAWIKI",
                "WIKIPEDIA",
                "S3",
                "R2",
                "GOOGLE_CLOUD_STORAGE",
                "OCI_STORAGE",
                "NOT_APPLICABLE",
                name="documentsource",
                native_enum=False,
            ),
            nullable=True,  # Initially allow NULL values
        ),
    )
    op.add_column(
        "credential",
        sa.Column(
            "name",
            sa.String(),
            nullable=True,
        ),
    )

    op.execute(
        """
    CREATE TEMPORARY TABLE temp_connector_credential AS
    SELECT DISTINCT ON (cc.credential_id)
        cc.credential_id,
        c.source AS connector_source
    FROM connector_credential_pair cc
    JOIN connector c ON cc.connector_id = c.id
    """
    )

    # Update the 'source' column in the 'credential' table
    op.execute(
        """
    UPDATE credential cred
    SET source = COALESCE(
        (SELECT connector_source
         FROM temp_connector_credential temp
         WHERE cred.id = temp.credential_id),
        'NOT_APPLICABLE'
    )
    """
    )
    # If no exception was raised, alter the column
    op.alter_column("credential", "source", nullable=True)  # TODO modify
    # # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_column("credential", "source")
    op.drop_column("credential", "name")
    # ### end Alembic commands ###
