"""Alter primary_owners secondary_owners to varchar

Revision ID: 568e07bfe178
Revises: fcd135795f21
Create Date: 2024-03-20 16:32:17.296621

"""
from alembic import op
import sqlalchemy as sa
from sqlalchemy.dialects import postgresql

# revision identifiers, used by Alembic.
revision = '568e07bfe178'
down_revision = 'fcd135795f21'
branch_labels = None
depends_on = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.execute("""
            ALTER TABLE document
            ALTER COLUMN primary_owners TYPE VARCHAR
            USING array_to_string(primary_owners, ', ')
        """)

    op.execute("""
            ALTER TABLE document
            ALTER COLUMN secondary_owners TYPE VARCHAR
            USING array_to_string(secondary_owners, ', ')
            """)

    op.execute("""
            ALTER TABLE document_chunk
            ALTER COLUMN primary_owners TYPE VARCHAR
            USING primary_owners::text
            """)

    op.execute("""
            ALTER TABLE document_chunk
            ALTER COLUMN secondary_owners TYPE VARCHAR
            USING secondary_owners::text
                """)
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.execute("""
            ALTER TABLE document
            ALTER COLUMN primary_owners TYPE character varying[]
            USING string_to_array(your_column_name, ', ')
        """)

    op.execute("""
            ALTER TABLE document
            ALTER COLUMN secondary_owners TYPE VARCHAR
            USING array_to_string(secondary_owners, ', ')
                """)

    op.execute("""
            ALTER TABLE document_chunk
            ALTER COLUMN primary_owners TYPE JSONB
            USING primary_owners::jsonb
            """)

    op.execute("""
            ALTER TABLE document_chunk
            ALTER COLUMN secondary_owners JSONB
            USING secondary_owners::jsonb
                    """)
    # ### end Alembic commands ###
