"""add cascade delete on two factor auth table

Revision ID: 5d10c5647eca
Revises: 24cad828e24c
Create Date: 2024-11-08 12:56:45.928700

"""
from alembic import op

# revision identifiers, used by Alembic.
revision = "5d10c5647eca"
down_revision = "24cad828e24c"
branch_labels = None
depends_on = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_constraint(
        "two_factor_auth_user_id_fkey", "two_factor_auth", type_="foreignkey"
    )
    op.create_foreign_key(
        None,
        "two_factor_auth",
        "user",
        ["user_id"],
        ["id"],
        ondelete="CASCADE",
    )
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_constraint(None, "two_factor_auth", type_="foreignkey")
    op.create_foreign_key(
        "two_factor_auth_user_id_fkey",
        "two_factor_auth",
        "user",
        ["user_id"],
        ["id"],
    )
    # ### end Alembic commands ###
