"""additional workspace data

Revision ID: 5f850f64e1c8
Revises: 680b0a25e46c
Create Date: 2024-09-07 15:01:31.587917

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = "5f850f64e1c8"
down_revision = "680b0a25e46c"
branch_labels = None
depends_on = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column(
        "workspace",
        sa.Column("workspace_description", sa.Text(), nullable=True),
    )
    op.add_column(
        "workspace", sa.Column("use_custom_logo", sa.Boolean(), nullable=False)
    )
    op.add_column(
        "workspace",
        sa.Column("custom_header_content", sa.Text(), nullable=True),
    )
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_column("workspace", "custom_header_content")
    op.drop_column("workspace", "use_custom_logo")
    op.drop_column("workspace", "workspace_description")
    # ### end Alembic commands ###
