"""added workspace id foreign key in key value store table

Revision ID: 680b0a25e46c
Revises: a5981c441686
Create Date: 2024-09-05 12:45:11.457535

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = "680b0a25e46c"
down_revision = "a5981c441686"
branch_labels = None
depends_on = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.alter_column(
        "instance",
        "subscription_plan",
        existing_type=sa.VARCHAR(length=10),
        nullable=True,
    )
    op.add_column(
        "key_value_store",
        sa.Column("workspace_id", sa.Integer(), nullable=True),
    )
    op.create_foreign_key(
        None, "key_value_store", "workspace", ["workspace_id"], ["id"]
    )
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_constraint(None, "key_value_store", type_="foreignkey")
    op.drop_column("key_value_store", "workspace_id")
    op.alter_column(
        "instance",
        "subscription_plan",
        existing_type=sa.VARCHAR(length=10),
        nullable=False,
    )
    # ### end Alembic commands ###
