"""standard answer categories to persona and global

Revision ID: 729fa47417b3
Revises: 5c7fdadae813
Create Date: 2024-09-16 12:07:08.615388

"""
from alembic import op
import sqlalchemy as sa

# revision identifiers, used by Alembic.
revision = "729fa47417b3"
down_revision = "c99d76fcd298"
branch_labels = None
depends_on = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table(
        "persona__standard_answer",
        sa.Column("persona_id", sa.Integer(), nullable=False),
        sa.Column("standard_answer_id", sa.Integer(), nullable=False),
        sa.ForeignKeyConstraint(
            ["persona_id"],
            ["persona.id"],
        ),
        sa.ForeignKeyConstraint(
            ["standard_answer_id"],
            ["standard_answer.id"],
        ),
        sa.PrimaryKeyConstraint("standard_answer_id"),
    )

    # Drop references to categories
    op.drop_table("slack_bot_config__standard_answer_category")
    op.drop_table("standard_answer__standard_answer_category")
    op.drop_table("standard_answer_category")

    op.add_column(
        "standard_answer",
        sa.Column(
            "apply_globally", sa.Boolean(), nullable=False, server_default=sa.true()
        ),
    )
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_column("standard_answer", "apply_globally")

    op.create_table(
        "standard_answer__standard_answer_category",
        sa.Column(
            "standard_answer_id",
            sa.INTEGER(),
            autoincrement=False,
            nullable=False,
        ),
        sa.Column(
            "standard_answer_category_id",
            sa.INTEGER(),
            autoincrement=False,
            nullable=False,
        ),
        sa.ForeignKeyConstraint(
            ["standard_answer_category_id"],
            ["standard_answer_category.id"],
            name="standard_answer__standard_answ_standard_answer_category_id_fkey",
        ),
        sa.ForeignKeyConstraint(
            ["standard_answer_id"],
            ["standard_answer.id"],
            name="standard_answer__standard_answer_catego_standard_answer_id_fkey",
        ),
        sa.PrimaryKeyConstraint(
            "standard_answer_id",
            "standard_answer_category_id",
            name="standard_answer__standard_answer_category_pkey",
        ),
    )
    op.create_table(
        "standard_answer_category",
        sa.Column(
            "id",
            sa.INTEGER(),
            server_default=sa.text(
                "nextval('standard_answer_category_id_seq'::regclass)"
            ),
            autoincrement=True,
            nullable=False,
        ),
        sa.Column("name", sa.VARCHAR(), autoincrement=False, nullable=False),
        sa.PrimaryKeyConstraint("id", name="standard_answer_category_pkey"),
        sa.UniqueConstraint("name", name="standard_answer_category_name_key"),
        postgresql_ignore_search_path=False,
    )
    op.create_table(
        "slack_bot_config__standard_answer_category",
        sa.Column(
            "slack_bot_config_id",
            sa.INTEGER(),
            autoincrement=False,
            nullable=False,
        ),
        sa.Column(
            "standard_answer_category_id",
            sa.INTEGER(),
            autoincrement=False,
            nullable=False,
        ),
        sa.ForeignKeyConstraint(
            ["slack_bot_config_id"],
            ["slack_bot_config.id"],
            name="slack_bot_config__standard_answer_cate_slack_bot_config_id_fkey",
        ),
        sa.ForeignKeyConstraint(
            ["standard_answer_category_id"],
            ["standard_answer_category.id"],
            name="slack_bot_config__standard_ans_standard_answer_category_id_fkey",
        ),
        sa.PrimaryKeyConstraint(
            "slack_bot_config_id",
            "standard_answer_category_id",
            name="slack_bot_config__standard_answer_category_pkey",
        ),
    )
    op.drop_table("persona__standard_answer")
    # ### end Alembic commands ###
