"""add expiry time
Revision ID: 91ffac7e65b3
Revises: bc9771dccadf
Create Date: 2024-06-24 09:39:56.462242
"""
from alembic import op
import sqlalchemy as sa

# revision identifiers, used by Alembic.
revision = "91ffac7e65b3"
down_revision = "bc9771dccadf"
branch_labels = None
depends_on = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column(
        "accesstoken", sa.Column("expiry_length", sa.Integer(), nullable=True)
    )
    op.add_column("user", sa.Column("oidc_expiry", sa.Integer(), nullable=True))


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_column("accesstoken", "expiry_length")

    op.drop_column("user", "oidc_expiry")

    # ### end Alembic commands ###
