"""workspaces relationship

Revision ID: 9fe292cac241
Revises: da12247ef2fc
Create Date: 2024-08-07 18:24:58.178981

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = "9fe292cac241"
down_revision = "da12247ef2fc"
branch_labels = None
depends_on = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    # op.drop_constraint("chat_message_id_key", "chat_message", type_="unique")
    op.add_column("user_group", sa.Column("workspace_id", sa.Integer(), nullable=False))
    op.create_foreign_key(
        "workspace__user_group",
        "user_group",
        "workspace",
        ["workspace_id"],
        ["workspace_id"],
    )
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_constraint("workspace__user_group_fk", "user_group", type_="foreignkey")
    op.drop_column("user_group", "workspace_id")
    op.create_unique_constraint("chat_message_id_key", "chat_message", ["id"])
    # ### end Alembic commands ###
