"""created created_at column for users

Revision ID: a5981c441686
Revises: 46eb3f54ab5b
Create Date: 2024-08-31 11:46:58.865629

"""
from alembic import op
import sqlalchemy as sa

# revision identifiers, used by Alembic.
revision = "a5981c441686"
down_revision = "46eb3f54ab5b"
branch_labels = None
depends_on = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column(
        "user",
        sa.Column(
            "created_at",
            sa.DateTime(timezone=True),
            server_default=sa.text("now()"),
            nullable=False,
        ),
    )
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_column("user", "created_at")
    # ### end Alembic commands ###
