"""user-teamspace relationship table update

Revision ID: a912ff7ae8c5
Revises: ea802eba7d25
Create Date: 2024-09-23 12:50:33.508639

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = "a912ff7ae8c5"
down_revision = "ea802eba7d25"
branch_labels = None
depends_on = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column(
        "user__teamspace",
        sa.Column(
            "role",
            sa.Enum("BASIC", "ADMIN", name="userrole", native_enum=False),
            nullable=False,
        ),
    )
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_column("user__teamspace", "role")
    # ### end Alembic commands ###
