apiVersion: v1
kind: ConfigMap
metadata:
  name: {{ .Values.config.envConfigMapName }}
  labels:
    {{- include "onyx-stack.labels" . | nindent 4 }}
data:
  INTERNAL_URL: "http://{{ include "onyx-stack.fullname" . }}-api-service:{{ .Values.api.service.port | default 8080 }}"
  POSTGRES_HOST: {{ include "onyx-stack.postgresHost" . }}
  VESPA_HOST: {{ include "onyx-stack.vespaHost" . }}
  REDIS_HOST: {{ include "onyx-stack.redisHost" . }}
  MODEL_SERVER_HOST: "{{ include "onyx-stack.fullname" . }}-inference-model-service"
  INDEXING_MODEL_SERVER_HOST: "{{ include "onyx-stack.fullname" . }}-indexing-model-service"
{{- range $key, $value := .Values.configMap }}
  {{ $key }}: "{{ $value }}"
{{- end }}
