name: Build Web Image on Merge Group

on:
  merge_group:
    types: [checks_requested]

env:
  REGISTRY_IMAGE: danswer/danswer-web-server

jobs:
  build:
    runs-on: 
      group: ${{ matrix.platform == 'linux/amd64' && 'amd64-image-builders' || 'arm64-image-builders' }}
    strategy:
      fail-fast: false
      matrix:
        platform:
          - linux/amd64
          - linux/arm64

    steps:
      - name: Prepare
        run: |
          platform=${{ matrix.platform }}
          echo "PLATFORM_PAIR=${platform//\//-}" >> $GITHUB_ENV          
      
      - name: Checkout
        uses: actions/checkout@v4
      
      - name: Docker meta
        id: meta
        uses: docker/metadata-action@v5
        with:
          images: ${{ env.REGISTRY_IMAGE }}
          tags: |
            type=raw,value=${{ env.REGISTRY_IMAGE }}:latest
      
      - name: Set up Docker Buildx
        uses: docker/setup-buildx-action@v3
    
      - name: Build by digest
        id: build
        uses: docker/build-push-action@v5
        with:
          context: ./web
          file: ./web/Dockerfile
          platforms: ${{ matrix.platform }}
          push: false
          build-args: |
            DANSWER_VERSION=v0.0.1
          # needed due to weird interactions with the builds for different platforms  
          no-cache: true
          labels: ${{ steps.meta.outputs.labels }}
